### ISSUE TITLE
Add your script to allow users to authorize Thunderbolt devices

### ISSUE THREAD

**Issue by Chaz6** [JMyklebust/Scripts#1]
Please consider adding your script from https://www.anitblog.no/uncategorized/drivers-thunderbolt-software-device-approval-without-local-admin/ to this repo as it is very useful!

**Comment by JMyklebust** [comment]
Uploaded now. :)

Also i realized too late that my commit setup was wrong... today i learned how to rewrite history. 😶
But of course GitHub won't cooperate on that....
